services:
  prometheus-service-demo-0:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-0
    ports:
      - "10000:8080"
    networks:
      - my_network

  prometheus-service-demo-1:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-1
    ports:
      - "20000:8080"
    networks:
      - my_network

  prometheus-service-demo-2:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-2
    ports:
      - "30000:8080"
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - prometheus-service-demo-0
      - prometheus-service-demo-1
      - prometheus-service-demo-2
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - my_network

volumes:
  grafana-storage:
    driver: local

networks:
  my_network:
    driver: bridge